version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    hostname: rmq
    ports:
      - 5672:5672
      - 8080:15672
  app:
    build:
      context: .
      dockerfile: Dockerfile